name: Soulcraft-Mobarena
version: 1.0
main: de.dal3x.mobarena.main.MobArenaPlugin
authors:
- DAL3X
- DrKeiter
- Keksilain
api-version: 1.15
commands: 
   mobarena:
      usage: /<command>
      description: Befehl zum nutzen der Mobarenen
      aliases: [moa]
   